### PR TITLE
docs: document contribution process

### PR DESCRIPTION
**Pull request by elvis-wolcott**
docs: add warning about breaking gradle update

fix: resolve lint warnings

test: skip push tests when running localy

### CODE REVIEW

**Comment by prisei1** [comment]
Hi there is still an error for PUB_KEY, please fix

Pada tanggal Jum, 28 Jun 2019 23:44, elvis-wolcott <notifications@github.com>
menulis:

**Comment by polarweasel** [comment]
@prisei1 care to be more specific?

**Comment by prisei1** [comment]
There is an error message from android studio when gradle project sync
finished. Its said "could not get unknown property 'PUB_KEY' for
DefaultConfig_Decorated ...... and so on

Pada tanggal Sab, 29 Jun 2019 22:16, Alex Ball <notifications@github.com>
menulis:

**Comment by qsoftdevelopment** [comment]
Hi @prisei1 

Your `gradle.properties` seems to be empty or it doesn’t exist. Either way, there is no `PUB_KEY` registered there.

Did you follow our readme.md guide? It’s available at https://github.com/pubnub/chat-examples-java

**Pull request merged**
